removing not needed demos + migrating to 5.0
hazelcast/hazelcast-demos pull request #1
Opened 2021-05-20 13:16 UTC by slavagithub

removing not needed demos + migrating to 5.0.
JetInstanse things are still them the code, we'll remove them once Hazelcast.bootstrappedInstance() is available

2021-05-20 13:16 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org/pull/badge/not_signed)](https://cla.hazelcast.org/hazelcast/hazelcast-demos?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.hazelcast.org/hazelcast/hazelcast-demos?pullRequest=1) before we can accept your contribution.<br/><hr/>**Viacheslav Sytnyk** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org/check/hazelcast/hazelcast-demos?pullRequest=1) it.</sub>

2021-05-20 21:17 UTC, olukas requested changes
@slavagithub please see inline comments.

Regarding `JetInstance` and `Hazelcast.bootstrappedInstance()` - if I understand it correctly, `Hazelcast.bootstrappedInstance()` should be replacement for `Jet.bootstrappedInstance()` but we still should use `JetInstance` for working with Jet, i.e. something like `JetInstance jet = Hazelcast.bootstrappedInstance().getJetInstance();`. 

And this is not replacement for `Jet.newJetInstance()`, we should use `Hazelcast.newHazelcastInstance().getJetInstance()` as replacement for it.

@ufukyilmaz can you please confirm that I understand it correctly? (AFAIK you're currently working on `Hazelcast.bootstrappedInstance()`)

2021-05-20 21:17 UTC, olukas commented on cryptocurrency-sentiment-analysis/README.md
> -# Twitter Cryptocurrency Sentiment Analysis
This demo is not supposed to be deleted!

2021-05-20 21:17 UTC, olukas commented on flight-telemetry/src/main/java/com/hazelcast/jet/demo/FlightTelemetry.java
> +            Hazelcast.shutdownAll();        }
Move `}` to another line

2021-05-20 21:17 UTC, olukas commented on flight-telemetry/src/main/java/com/hazelcast/jet/demo/FlightTelemetry.java
> +        return Jet.bootstrappedInstance();
This makes no sense to me - boostrap instance should be used if this `bootstrap != null && bootstrap.equals("true")` is true (previous condition). I guess migration of `Jet.newJetInstance()` should not be `Jet.bootstrappedInstance()` but `Hazelcast.newHazelcastInstance().getJetInstance()`. 

The same should be applied for the other replacements `Jet.newJetInstance()` by `Jet.bootstrappedInstance()` in this PR.

Also please remove the commented code.

2021-05-20 21:17 UTC, olukas commented on pom.xml
> +        <hazelcast-jet.version>5.0-SNAPSHOT</hazelcast-jet.version>
We should rename `hazelcast-jet.version` to `hazelcast.version`

2021-05-20 21:17 UTC, olukas commented on road-traffic-predictor/src/main/resources/log4j.properties
> +log4j.logger.com.hazelcast.jet=debug
Is this change (and change for `log4j.appender.stdout.layout.ConversionPattern`) intended or it's leftover?

2021-05-20 21:17 UTC, olukas commented on pom.xml
> +    <version>5.0</version>
This should be `5.0-SNAPSHOT` version (and the version should be updated in submodules)

2021-05-20 21:17 UTC, olukas commented on pom.xml
> +    <groupId>com.hazelcast.platform.demos</groupId>
I don't think `platform` should be used in `groupId` and `artifactId`. This makes more sense:
```
groupId=com.hazelcast.demos
artifactId=hazelcast-demos
```
@vladoschreiner WDYT?

2021-05-20 21:17 UTC, olukas commented on pom.xml
> +        <repository>
Is this repository actually needed?

2021-05-21 06:52 UTC, ufukyilmaz commented
> @slavagithub please see inline comments.
> 
> Regarding `JetInstance` and `Hazelcast.bootstrappedInstance()` - if I understand it correctly, `Hazelcast.bootstrappedInstance()` should be replacement for `Jet.bootstrappedInstance()` but we still should use `JetInstance` for working with Jet, i.e. something like `JetInstance jet = Hazelcast.bootstrappedInstance().getJetInstance();`.
> 
> And this is not replacement for `Jet.newJetInstance()`, we should use `Hazelcast.newHazelcastInstance().getJetInstance()` as replacement for it.
> 
> @ufukyilmaz can you please confirm that I understand it correctly? (AFAIK you're currently working on `Hazelcast.bootstrappedInstance()`)

Hi @olukas , All what you said is true. To add to this discussion, we deprecate `Jet` class and all of the static factory methods of it (Jet was the main entry point for old Jet product), because we wanted the entry point of this merged product to be the `Hazelcast` class. Users will get `HazelcastInstance` using the methods of this Hazelcast class. Then, if they want to access `JetInstance`, they can get it only from `HazelcastInstance` by calling the `HazelcastInstance#getJetInstance()`. This will be only way to access `JetInstance` unless they use deprecated methods.

To list all the replacements:

- `Jet.newJetInstance()` should be replaced by `Hazelcast.newHazelcastInstance().getJetInstance()`
- `Jet.newJetClient()` -> `HazelcastClient.newHazelcastClient().getJetInstance()`
- `Jet.bootstrappedInstance()` or `JetBootstrap.getJetInstance()`(which is a usage of the internal API that we are removing in 5.0) -> `Hazelcast.bootstrappedInstance().getJetInstance()`
- `Jet.newJetFailoverClient()` -> `HazelcastClient.newHazelcastFailoverClient()`

2021-05-21 07:00 UTC, ufukyilmaz commented
btw, https://github.com/hazelcast/hazelcast/pull/18672 including `Hazelcast.bootstrappedInstance()` changes, is not merged yet. It will be merged very soon.

2021-05-26 14:08 UTC, slavagithub commented on flight-telemetry/src/main/java/com/hazelcast/jet/demo/FlightTelemetry.java
> +        return Jet.bootstrappedInstance();
This is done

2021-05-26 14:10 UTC, slavagithub commented on flight-telemetry/src/main/java/com/hazelcast/jet/demo/FlightTelemetry.java
> +            Hazelcast.shutdownAll();        }
It seems this is a common approach for "finally". It is in HZ code and Idea default formatted puts it into that way. Could we please discuss common approach?

2021-05-26 14:11 UTC, slavagithub commented on pom.xml
> +        <hazelcast-jet.version>5.0-SNAPSHOT</hazelcast-jet.version>
This is done

2021-05-26 14:17 UTC, slavagithub commented on road-traffic-predictor/src/main/resources/log4j.properties
> +log4j.logger.com.hazelcast.jet=debug
leftover, removed :)

2021-05-26 14:20 UTC, slavagithub commented on pom.xml
> +    <version>5.0</version>
It's done

2021-05-26 14:21 UTC, slavagithub commented on pom.xml
> +    <groupId>com.hazelcast.platform.demos</groupId>
It seems this is a good idea, since we not a platform anymore)

2021-05-26 14:29 UTC, slavagithub commented on pom.xml
> +        <repository>
I don't think so. Removed

2021-05-26 17:46 UTC, slavagithub commented on cryptocurrency-sentiment-analysis/README.md
> -# Twitter Cryptocurrency Sentiment Analysis
added, but changes will go in separate PR - there is some work with Twitter Hazelcast library

2021-05-27 11:51 UTC, olukas commented on flight-telemetry/src/main/java/com/hazelcast/jet/demo/FlightTelemetry.java
> +            Hazelcast.shutdownAll();        }
It is definitely not common approach at all. If Idea put it to the same line I guess it's a bug in Idea. Ending `}` should be on the new line, I have never seen code like this:
```
        } finally {
            Hazelcast.shutdownAll();        }
```
It should be:
```
        } finally {
            Hazelcast.shutdownAll();
        }
```

However, this indicate we should apply some checkstyles rules to `hazelcast-demos` repo. I tried to run `grep "\;.*  }" -R . | grep "\.java:" | wc -l` and it give 47 results for `hazelcast-demos` repo. Things like this should not occur in our code.

2021-05-27 13:02 UTC, olukas approved these changes
LGTM thanks. Please fix mentioned checkstyle issue before merge and check whether removing of `cryptocurrency-sentiment-analysis/src/main/resources/twitter-security.properties` is expected.

2021-05-27 13:02 UTC, olukas commented on cryptocurrency-sentiment-analysis/src/main/resources/twitter-security.properties
> -consumerKey=REPLACE_THIS
I guess this file should not be removed, right?

2021-05-31 08:01 UTC, slavagithub commented on flight-telemetry/src/main/java/com/hazelcast/jet/demo/FlightTelemetry.java
> +            Hazelcast.shutdownAll();        }
yes, this example is 100% correct, will refactor where possible

2021-06-01 11:51 UTC, slavagithub commented on cryptocurrency-sentiment-analysis/src/main/resources/twitter-security.properties
> -consumerKey=REPLACE_THIS
it should be with REPLACE_THIS for all keys

2021-06-01 13:49 UTC, merged