HZC-1896: Add TLS related details for the Hazelcast Cloud Trade Monitor demo
hazelcast/hazelcast-demos pull request #10
Opened 2021-10-20 12:44 UTC by sdreger

2021-10-21 17:49 UTC, vladoschreiner requested changes
Minor changes. The whole flow was tested and works fine.

2021-10-21 17:49 UTC, vladoschreiner commented on realtime-trade-monitor/README.md
>  1. Create Enterprise Hazelcast cluster in https://cloud.hazelcast.com/
I believe that the cluster must be set to _Public access._

2021-10-21 17:49 UTC, vladoschreiner commented on realtime-trade-monitor/README.md
>      hazelcast.client.cloud.url: "https://uat.hazelcast.cloud" #Optional, if env is not default
Stay consistent with the environemnts. The first step expected the cluster to be created on PROD.

2021-10-21 17:49 UTC, vladoschreiner commented on realtime-trade-monitor/README.md
> +
The API_KEY and SECRET placeholders must be replaced with the values available in Confluent.cloud (Data integration > API Keys).

2021-10-21 17:49 UTC, vladoschreiner commented on realtime-trade-monitor/README.md
>    properties:
Please make sure that the hazelcast client config files is valid once # character is deleted (once the cloud configs are uncommented). Especially the indentation. There are people who don't work with YAML and might get confused by how much spaces to add.

2021-10-22 06:44 UTC, sdreger commented on realtime-trade-monitor/README.md
>  1. Create Enterprise Hazelcast cluster in https://cloud.hazelcast.com/
Agree, added.

2021-10-22 06:44 UTC, sdreger commented on realtime-trade-monitor/README.md
>    properties:
Both configs are valid and tested and can be safely copy-pasted, all the comments were removed.

2021-10-22 06:44 UTC, sdreger commented on realtime-trade-monitor/README.md
>      hazelcast.client.cloud.url: "https://uat.hazelcast.cloud" #Optional, if env is not default
Agree, removed that line, it is not needed for the `prod` env.

2021-10-22 07:18 UTC, huseyinbabal commented on realtime-trade-monitor/README.md
> +6. Create topic `trades` with 4 partitions. If you use https://confluent.cloud go to Topics section in the UI.
`...If you already use https://confluent.cloud, go to ...` mind the comma

2021-10-22 07:20 UTC, huseyinbabal commented on realtime-trade-monitor/README.md
> +12. Browse to localhost:9000 to see the dashboard.
what about making this a real link? instead of copy paste to browser, user can just click

2021-10-22 07:21 UTC, huseyinbabal approved these changes
Ok with minor comments

2021-12-09 08:41 UTC, vladoschreiner approved these changes

2021-12-09 08:43 UTC, merged