adding migrated trade-monitor
hazelcast/hazelcast-demos pull request #3
Opened 2021-05-29 18:48 UTC by slavagithub

the trade-monitor demo has been migrated to 5.0 and added to the project

2021-05-31 12:20 UTC, olukas requested changes
Hi @slavagithub , is this really ready for review? Current version has couple of obvious mistakes:
- project cannot be even built because of mistakes in pom.xml files (in `artifact-id`s)
- there is missing `modules` in `realtime-trade-monitor/pom.xml`
- `realtime-image-recognition` is removed from pom.xml in this PR
- README is missing at all

Have you tried to build it and run it from this branch? After cloning the repo `mvn install` command has to build all relevant artifacts for all demos.

2021-05-31 14:02 UTC, slavagithub commented
@olukas my bad, correct version is committed. Please take a look

2021-05-31 16:11 UTC, olukas reviewed
Couple of minor issues. Generally LGTM, thanks.

2021-05-31 16:11 UTC, olukas commented on realtime-trade-monitor/README.md
> +A sample dashboard which uses [Hazelcast Jet](https://github.com/hazelcast/hazelcast-jet)
We shouldn't link legacy https://github.com/hazelcast/hazelcast-jet here

2021-05-31 16:11 UTC, olukas commented on realtime-trade-monitor/README.md
> +java -jar webapp/target/webapp-5.0-SNAPSHOT.jar
`webapp` dir was renamed to `web-app` => this doesn't work

2021-05-31 16:11 UTC, olukas commented on realtime-trade-monitor/trade-queries/pom.xml
> +            <version>5.0-SNAPSHOT</version>
It shouldn't be hard-coded here.

2021-05-31 16:11 UTC, olukas commented on realtime-trade-monitor/trade-queries/src/main/java/App.java
> +
Remove useless empty lines here

2021-05-31 16:11 UTC, olukas commented on realtime-trade-monitor/trade-queries/src/main/java/Benchmark.java
> +//import com.hazelcast.jet.IMapJet;
This should be removed

2021-05-31 16:11 UTC, olukas commented on realtime-trade-monitor/trade-queries/src/main/java/BenchmarkLatency.java
> +//import com.hazelcast.IMapJet;
This should be removed

2021-05-31 16:11 UTC, olukas commented on realtime-trade-monitor/trade-queries/src/main/java/LoadSymbols.java
> +//import com.hazelcast.jet.IMapJet;
This should be removed

2021-05-31 16:11 UTC, olukas commented on realtime-trade-monitor/trade-queries/src/main/java/LoadSymbols.java
> +//import com.hazelcast.jet.server.JetBootstrap;
This should be removed

2021-06-01 11:01 UTC, slavagithub commented on realtime-trade-monitor/README.md
> +A sample dashboard which uses [Hazelcast Jet](https://github.com/hazelcast/hazelcast-jet)
changed to demos

2021-06-01 11:04 UTC, slavagithub commented on realtime-trade-monitor/README.md
> +java -jar webapp/target/webapp-5.0-SNAPSHOT.jar
reverted

2021-06-01 11:05 UTC, slavagithub commented on realtime-trade-monitor/trade-queries/pom.xml
> +            <version>5.0-SNAPSHOT</version>
changed to property

2021-06-01 11:07 UTC, slavagithub commented on realtime-trade-monitor/trade-queries/src/main/java/App.java
> +
removed

2021-06-01 11:07 UTC, slavagithub commented on realtime-trade-monitor/trade-queries/src/main/java/Benchmark.java
> +//import com.hazelcast.jet.IMapJet;
removed

2021-06-01 11:08 UTC, slavagithub commented on realtime-trade-monitor/trade-queries/src/main/java/BenchmarkLatency.java
> +//import com.hazelcast.IMapJet;
removed

2021-06-01 11:08 UTC, slavagithub commented on realtime-trade-monitor/trade-queries/src/main/java/LoadSymbols.java
> +//import com.hazelcast.jet.IMapJet;
removed

2021-06-01 11:08 UTC, slavagithub commented on realtime-trade-monitor/trade-queries/src/main/java/LoadSymbols.java
> +//import com.hazelcast.jet.server.JetBootstrap;
cleaned up

2021-06-01 11:27 UTC, slavagithub commented
All PR review issues have been fixed. Merging this.

2021-06-01 11:29 UTC, merged

2021-06-01 11:32 UTC, olukas commented on realtime-trade-monitor/README.md
> +A sample dashboard which uses [Hazelcast Jet](https://github.com/hazelcast/hazelcast-jet)
It doesn't make sense to change it to `[Hazelcast Demo](https://github.com/hazelcast/hazelcast-demo)`. It should change the link to https://github.com/hazelcast/hazelcast, using a term "Hazelcast Jet" is ok.

2021-06-01 11:34 UTC, slavagithub commented on realtime-trade-monitor/README.md
> +A sample dashboard which uses [Hazelcast Jet](https://github.com/hazelcast/hazelcast-jet)
make sense, will correct